<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-RafaeladaCunha/blob/main/1_Vetor_de_zeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Atividade1
import numpy as np
array = np.zeros(10)
print(array)

print(array.shape)
print(array.dtype)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
float64


In [ ]:
#Atividade2

import numpy as np
array = np.ones(10)
print(array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Atividade3


array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Atividade4
matriz = np.arange(9).reshape(3, 3)
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Atividade5
import numpy as np

v = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(v)
print(indices)



(array([0, 1, 4]),)


In [ ]:
#Atividade6
import numpy as np

vetor = np.linspace(0, 1, 12)
print("Vetor linspace:\n", vetor)


Vetor linspace:
 [0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [ ]:
#Atividade7
import numpy as np

identidade = np.eye(5)
print("\nMatriz identidade 5x5:\n", identidade)


Matriz identidade 5x5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Atividade 8
import numpy as np
rng = np.random.default_rng(42)
aleatorio = rng.uniform(0, 1, (3, 3, 3))
print("\nArray aleatório 3x3x3:\n", aleatorio)


Array aleatório 3x3x3:
 [[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


In [ ]:
#Atividade 9.
import numpy as np

rng = np.random.default_rng(42)
matriz = rng.uniform(0, 1, (10, 10))

min_val = matriz.min()
max_val = matriz.max()

print("Matriz 10x10:\n", matriz)
print("\nValor mínimo:", min_val)
print("Valor máximo:", max_val)

Matriz 10x10:
 [[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
  0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142  0.22723872
  0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835  0.19463871
  0.466721   0.04380377 0.15428949 0.68304895]
 [0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
  0.12992151 0.47570493 0.22690935 0.66981399]
 [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598  0.80476436
  0.38747838 0.2883281  0.6824955  0.13975248]
 [0.1999082  0.00736227 0.78692438 0.66485086 0.70516538 0.78072903
  0.45891578 0.5687412  0.139797   0.11453007]
 [0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
  0.55920716 0.3039501  0.03081783 0.43671739]
 [0.21458467 0.40852864 0.85340307 0.23393949 0.05830274 0.28138389
  0.29359376 0.66191651 0.55703215 0.78389821]
 [0.66431354 0.40638686 0.81402038 0.16697292 0.02271207 0.0900478

In [ ]:
#Atividade 10
import numpy as np

x = np.array([1, 2, 3, 4, 5], dtype=float)

x_normalizado = (x - x.mean()) / x.std()

print("Array original:", x)
print("Array padronizado:", x_normalizado)


Array original: [1. 2. 3. 4. 5.]
Array padronizado: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
#Atividade 11

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original (int32):", arr, arr.dtype)

arr_float = arr.astype(np.float32)
print("Convertido para float32:", arr_float, arr_float.dtype)

arr_int64 = arr_float.astype(np.int64)
print("Convertido para int64:", arr_int64, arr_int64.dtype)



Original (int32): [1 2 3] int32
Convertido para float32: [1. 2. 3.] float32
Convertido para int64: [1 2 3] int64


In [ ]:
#Atividade 12

import numpy as np

a = np.array([2, 5, 7, 1, 9])
a_clip = np.clip(a, 0, 5)

print("Original:", a)
print("Após clipping [0,5]:", a_clip)




Original: [2 5 7 1 9]
Após clipping [0,5]: [2 5 5 1 5]


In [ ]:
#Atividade 13

import numpy as np

vetor = np.arange(10)
vetor_invertido = np.flip(vetor)

print("Vetor original:", vetor)
print("Vetor invertido:", vetor_invertido)


Vetor original: [0 1 2 3 4 5 6 7 8 9]
Vetor invertido: [9 8 7 6 5 4 3 2 1 0]


In [ ]:
#Atividade 14
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

horizontal = np.hstack((a, b))
vertical = np.vstack((a, b))

print("Horizontal:\n", horizontal)
print("\nVertical:\n", vertical)


Horizontal:
 [1 2 3 4 5 6]

Vertical:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#Atividade 15
import numpy as np

matriz = np.eye(4) * 5
print(matriz)



[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


In [ ]:
#Atividade 16
import numpy as np

A = np.arange(12).reshape(3, 4)
soma_linhas = A.sum(axis=1)
soma_colunas = A.sum(axis=0)

print("Soma por linhas:", soma_linhas)
print("Soma por colunas:", soma_colunas)


Soma por linhas: [ 6 22 38]
Soma por colunas: [12 15 18 21]


In [ ]:
#Atividade 17
import numpy as np

valores = np.random.randint(0, 10, size=100)
frequencias = np.bincount(valores, minlength=10)

print("Frequências:", frequencias)


Frequências: [ 9 15  8 11 10  7 13  8 13  6]


In [ ]:
#Atividade 18
import numpy as np

v = np.arange(20)
resultado = v[1::3]
print("Cada 3º elemento a partir do índice 1:", resultado)


Cada 3º elemento a partir do índice 1: [ 1  4  7 10 13 16 19]


In [ ]:
#Atividade 19
import numpy as np
v = np.arange(20)
mascara_pares = v % 2 == 0
pares = v[mascara_pares]
print("Números pares:", pares)


Números pares: [ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
#Atividade 20
import numpy as np
lista = [[1, 2, 3], [4, 5, 6]]
array = np.array(lista)

print("Array:", array)
print("Shape:", array.shape)
print("Dtype:", array.dtype)


Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64


In [ ]:
#Atividade 21
import numpy as np
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print("Datas:", datas)


Datas: ['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


In [ ]:
#Atividade 22
import numpy as np
A = np.array([[1., 2., 3.], [4., 5., 6.]])
media_colunas = A.mean(axis=0)
centralizado = A - media_colunas

print("Matriz centralizada por coluna:\n", centralizado)


Matriz centralizada por coluna:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [ ]:
#Atividade 23
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

produto_elemento = a * b
produto_escalar = np.dot(a, b)

print("Produto elemento a elemento:", produto_elemento)
print("Produto escalar:", produto_escalar)


Produto elemento a elemento: [ 4 10 18]
Produto escalar: 32


In [ ]:
#Atividade 24
import numpy as np

A = np.arange(12).reshape(3, 4)
A[:, [0, 2]] = A[:, [2, 0]]

print("Matriz com colunas 0 e 2 trocadas:\n", A)


Matriz com colunas 0 e 2 trocadas:
 [[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


In [ ]:
#Atividade 25
import numpy as np

a = np.array([[1, 2], [3, 4]])

flat = a.flatten()
ravel_view = a.ravel()

ravel_view[0] = 99

print("Original:\n", a)
print("flatten (cópia):", flat)
print("ravel (view):", ravel_view)



Original:
 [[99  2]
 [ 3  4]]
flatten (cópia): [1 2 3 4]
ravel (view): [99  2  3  4]


In [ ]:
#Atividade 26
import numpy as np
tabuleiro = np.zeros((8, 8), dtype=int)
tabuleiro[1::2, ::2] = 1
tabuleiro[::2, 1::2] = 1
print(tabuleiro)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Atividade 27
import numpy as np
x = np.arange(-5, 6)
resultado = np.where(x < 0, 0, x)
print(resultado)



[0 0 0 0 0 0 1 2 3 4 5]


In [ ]:
#Atividade 28
import numpy as np
dados = np.random.rand(1_000_000)
media = dados.mean()
erro_absoluto = abs(media - 0.5)

print("Média:", media)
print("Erro absoluto:", erro_absoluto)



Média: 0.49977982395047443
Erro absoluto: 0.00022017604952556669


In [ ]:
#Atividade 29
import numpy as np
a = np.array([1, 2, 3])[:, None]
b = np.array([10, 20, 30, 40])
somas = a + b
print(somas)



[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [ ]:
#Atividade 30
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

s = np.array([1, 2, 3, 4, 5])
k = np.array([1, 0, -1])

k_flip = np.flip(k)
janelas = sliding_window_view(s, len(k))
resultado = (janelas * k_flip).sum(axis=1)

print("Resultado da convolução:", resultado)



Resultado da convolução: [2 2 2]


In [ ]:
#Atividade 31
import numpy as np

rng = np.random.default_rng()
A = rng.normal(size=(5, 4))

minimos = A.min(axis=0)
maximos = A.max(axis=0)
intervalos = maximos - minimos
intervalos[intervalos == 0] = 1

normalizado = (A - minimos) / intervalos
print("Matriz normalizada:\n", normalizado)



Matriz normalizada:
 [[0.32825787 0.6432991  0.         0.40806302]
 [1.         1.         0.35589594 1.        ]
 [0.94974098 0.         1.         0.        ]
 [0.         0.10545379 0.68114942 0.20962782]
 [0.27462103 0.58633313 0.32298647 0.29277775]]


In [ ]:
#Atividade 32
import numpy as np
A = np.array([[3, 9], [1, 4], [2, 5]])
ordenado = A[A[:, 1].argsort()]
print(ordenado)


[[1 4]
 [2 5]
 [3 9]]


In [ ]:
#Atividade 33
import numpy as np
x = np.array([3, 1, 2, 3, 2, 3, 1])
valores, contagens = np.unique(x, return_counts=True)
_, idx_primeira = np.unique(x, return_index=True)

print("Valores únicos:", valores)
print("Contagens:", contagens)
print("Índices da 1ª ocorrência:", idx_primeira)


Valores únicos: [1 2 3]
Contagens: [2 2 3]
Índices da 1ª ocorrência: [1 2 0]


In [ ]:
#Atividade 34
import numpy as np
P = np.random.rand(5, 2)
difs = P[:, None, :] - P[None, :, :]
distancias = np.sqrt(np.sum(difs**2, axis=2))

print("Matriz de distâncias:\n", distancias)


Matriz de distâncias:
 [[0.         0.64935467 0.65521031 0.47871725 0.5374665 ]
 [0.64935467 0.         0.78117116 1.10413798 1.1789864 ]
 [0.65521031 0.78117116 0.         0.7593876  0.87033899]
 [0.47871725 1.10413798 0.7593876  0.         0.11129628]
 [0.5374665  1.1789864  0.87033899 0.11129628 0.        ]]


In [ ]:
#Atividade 35
import numpy as np

dados = np.random.randn(1000, 3)

cov = np.cov(dados, rowvar=False)
corr = np.corrcoef(dados, rowvar=False)

print("Covariância:\n", cov)
print("Correlação:\n", corr)


Covariância:
 [[ 0.96761721 -0.00859742  0.01733561]
 [-0.00859742  1.05648474  0.11501101]
 [ 0.01733561  0.11501101  1.06510455]]
Correlação:
 [[ 1.         -0.00850325  0.0170762 ]
 [-0.00850325  1.          0.10842057]
 [ 0.0170762   0.10842057  1.        ]]


In [ ]:
#Atividade 36
import numpy as np
y = np.array([2, 0, 1, 2])
n_classes = y.max() + 1
one_hot = np.eye(n_classes)[y]

print("One-hot:\n", one_hot)


One-hot:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Atividade 37

import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])


x_mean = np.mean(x)
y_mean = np.mean(y)


B1 = np.sum((x - x_mean) * (y - y_mean)) / np.sum((x - x_mean) ** 2)


B0 = y_mean - B1 * x_mean

print(f"Slope (B1): {B1}")
print(f"Intercept (B0): {B0}")


y_pred = B0 + B1 * x
print("Predicted values:", y_pred)

Slope (B1): 0.6
Intercept (B0): 2.2
Predicted values: [2.8 3.4 4.  4.6 5.2]


In [ ]:
#Atividade 37

import numpy as np

np.random.seed(0)
X = np.random.rand(100, 2)
K = 3
centroides = X[np.random.choice(X.shape[0], K, replace=False)]

def dist_euclidiana(a, b):
    return np.linalg.norm(a - b, axis=1)

for i in range(10):

    distancias = np.array([dist_euclidiana(X, c) for c in centroides])
    clusters = np.argmin(distancias, axis=0)


    novos_centroides = np.array([X[clusters == j].mean(axis=0) for j in range(K)])


    if np.allclose(centroides, novos_centroides):
        break

    centroides = novos_centroides

print("Centróides finais:", centroides)


Centróides finais: [[0.76167338 0.40765364]
 [0.27223715 0.21097997]
 [0.35217863 0.78488734]]


In [ ]:
#Atividade 38
import numpy as np

np.random.seed(0)
X = np.random.rand(100, 2)
X_centered = X - np.mean(X, axis=0)

cov_matrix = np.cov(X_centered.T)

autovalores, autovetores = np.linalg.eig(cov_matrix)

projecao_1D = X_centered.dot(autovetores[:, 0])

X_reconstruido = projecao_1D[:, np.newaxis] * autovetores[:, 0]

print("Autovetores:", autovetores)
print("Dados projetados em 1D:", projecao_1D[:5])


Autovetores: [[-0.77572974  0.63106527]
 [-0.63106527 -0.77572974]]
Dados projetados em 1D: [-0.17109113 -0.10546734 -0.03027198 -0.19624539 -0.28354749]


In [ ]:
#Atividade 39
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view


imagem = np.random.rand(5, 5)
kernel = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

blocos = sliding_window_view(imagem, kernel.shape)

saida = np.tensordot(blocos, kernel, axes=((2, 3), (0, 1)))

print("Resultado da convolução:", saida)



Resultado da convolução: [[-0.12514243  0.61312798  0.55252587]
 [ 0.31572829 -0.17191179 -0.24813181]
 [ 1.05761531 -0.24012153  0.28274873]]


In [ ]:
#Atividade 40
import numpy as np

A = np.random.rand(100, 100)
b = np.random.rand(100)

x = np.linalg.solve(A, b)

residuo = np.linalg.norm(np.dot(A, x) - b) / np.linalg.norm(b)

cond_A = np.linalg.cond(A)

print("Resíduo relativo:", residuo)
print("Condicionamento de A:", cond_A)


Resíduo relativo: 8.333990602492656e-15
Condicionamento de A: 1977.110704711245


In [ ]:
#Atividade 41

import numpy as np

X = np.random.rand(100, 3)
y = np.random.rand(100)

coef, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

y_pred = X.dot(coef)

rmse = np.sqrt(np.mean((y - y_pred) ** 2))

print("Coeficientes:", coef)
print("RMSE:", rmse)


Coeficientes: [0.31575994 0.2533532  0.24077049]
RMSE: 0.3150707372927383


In [ ]:
#Atividade 42

import numpy as np
from numpy.lib.stride_tricks import sliding_window_view


imagem = np.random.rand(5, 5)


janelas = sliding_window_view(imagem, (3, 3))


media_local = janelas.mean(axis=(2, 3))

print("Média local 3x3:", media_local)




Média local 3x3: [[0.45761396 0.42363756 0.43347198]
 [0.50140696 0.3976204  0.37239241]
 [0.46839743 0.34761143 0.46138036]]
